# site properties and page defaults
title: Information Visions Lab
subtitle: CU Boulder Information Science
description: The Information Visions Lab @ CU Boulder imagines a future of data communication that prioritizes equity & access. Our research draws on vis tools and techniques to empower how diverse communities trust, create, and engage with data. 
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: evan.peck@colorado.edu
  github: infovisions
  # TODO: get bluesky here

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  # - jekyll-last-modified-at (removed because of trouble)

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
